bonaproject/bonaapp/urls.py
from django.urls import path
from .views import *


urlpatterns = [
    path('', home_page, name='home_page'),
    path('category/<pk>', category_detail, name='category_detail'),
    path('cart/', cart, name='cart_url'),
    path('add_to_cart/<pk>', add_to_cart, name='add_to_cart_url'),
    path('delete_cart_item/', delete_cart_item, name='delete_cart_item'),
    path('product_detail/<pk>', product_detail, name='product_detail_url'),
    path('create_order/', create_order, name='create_order_url'),
    path('history_order/', history_order, name='history_order_url'),
    path('buy_later/<pk>', buylater, name='buy_later_url'),
    path('return_order/<pk>', return_order, name='return_order_url'),
    path('buy_now/<pk>', buynow, name='buy_now_url'),
    path('about/', about, name='about_url')
]

bonaproject/bonaproject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('bonaapp.urls', 'bonafressco'), namespace='bonaapp')),
    path('users/', include(('bonausers.urls', 'bonafressco'), namespace='bonausers')),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL , document_root = settings.MEDIA_ROOT)

bonaproject/bonausers/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path('signup/', signup, name='signup'),
    path('login/', log_in, name='login'),
    path('logout/', sign_out, name='logout'),
]

bonaproject/bonaapp/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.


class Category(models.Model):
	name = models.CharField(max_length=100)
	image = models.ImageField(upload_to='images/')

	def __str__(self):
		return f'name: {self.name}'

class Product(models.Model):
	COUNTRY_CHOICES = (
		('UZ' , 'UZBEKISTAN'),
		('RU' , 'RUSSIA'),
		('AZE' , 'AZERBAIJAN'),
		('TURK' , 'TURKEY'),
		('UAE' , 'UAE'),
		('UKR' , 'UKRAINE'),
		('IRAN' , 'IRAN'),
	)
	name = models.CharField(max_length=100)
	image = models.ImageField(upload_to='images/')
	description = models.TextField(null = True)
	price = models.FloatField()
	quantity = models.FloatField()
	discounted_product = models.BooleanField(default=False, blank=True, null=True)
	discounted_price = models.IntegerField(blank=True, null=True)
	product_category = models.ForeignKey(Category, on_delete= models.CASCADE)
	country = models.CharField(max_length=100,choices = COUNTRY_CHOICES)
	date = models.DateTimeField(auto_now_add=True)

	def __str__(self):
		return f'product: {self.name}  , quantity : {self.quantity}'


class Basket(models.Model):
	owner = models.ForeignKey(User, on_delete = models.CASCADE)
	product = models.ForeignKey(Product, on_delete = models.CASCADE)
	quantity = models.FloatField()

	def __str__(self):
		return f'owner : {self.owner}'

	def total_price(self):
		return self.product.price * self.quantity


class Order(models.Model):
	address = models.CharField(max_length=255)
	email = models.EmailField(max_length=254)
	telephone_number = models.CharField(max_length=255)
	owner = models.ForeignKey(User, on_delete=models.CASCADE)
	buy = models.BooleanField(default=False)
	date = models.DateTimeField(auto_now_add=True, null=True)

	def __str__(self):
		return f'owner : {self.owner} '





class OrderProduct(models.Model):
	product = models.ForeignKey(Product, on_delete=models.CASCADE, null=True)
	order = models.ForeignKey(Order, on_delete=models.CASCADE, related_name='order_product')
	amount = models.FloatField(default=0)
	total = models.PositiveIntegerField(default=0)

	def __str__(self):
		return f'owner : {self.order.owner} |product: {self.product} |total {self.amount} kg \ ltr |price {self.total} AED'


class Slider(models.Model):
	image = models.ImageField(upload_to='slider/')
	product = models.ForeignKey(Product, on_delete=models.CASCADE, null=True , blank=True)
	description = models.CharField(max_length=255 , null=True , blank=True)

	def __str__(self):
		return f"slider"

class BuyLater(models.Model):
	quantity = models.FloatField()
	date = models.DateTimeField()
	owner = models.ForeignKey(User, on_delete=models.CASCADE)
	product = models.ForeignKey(Product, on_delete=models.CASCADE , null=True)

	def __str__(self):
		return f'owner : {self.owner}'

	def total_price(self):
		return self.product.price * self.quantity

bonaproject/bonaapp/forms.py
from django import forms
from .models import Order


class CrateOrder(forms.ModelForm):
    address = forms.CharField(help_text='address', widget=forms.TextInput(attrs={'class':'input', 'name':'address'}))
    email = forms.EmailField(help_text='email', widget=forms.EmailInput(attrs={'class':'input', 'name':'email'}))
    telephone_number = forms.IntegerField(help_text='number', widget=forms.TextInput(attrs={'class':'input', 'name':'telephone_number'}))

    class Meta:
        model = Order
        fields = ['address','email','telephone_number']

bonaproject/bonaapp/views.py
from django.shortcuts import render, redirect
from .models import *
from .forms import *
from django.contrib import messages
import datetime
from django.db.models import Q
from django.core.mail import send_mail
# Create your views here.


def home_page(request):
    search = request.GET.get('search')
    product = Product.objects.all()
    result = None
    products = None
    if search:
        products = product.filter(Q(name__icontains=search))
        if product:result = True
    slider = Slider.objects.all()
    return render(request, 'home_page.html', {
        'product':product,
        'products':products,
        'slider':slider,
        'result':result,
        'search':search
    })

def category_detail(request,pk):
    categorys = Category.objects.get(pk=pk)
    return render(request, 'category-detail.html', {'category':categorys})

# cart create

def add_to_cart(request,pk):
    kol = float(request.GET.get('kol'))
    if kol > 0:
        product = Product.objects.get(pk=pk)
        basket = Basket.objects.filter(owner=request.user, product=product)
        for item in basket:
            if item.product == product:
                item.quantity = kol
                item.save()
                return redirect('bonaapp:cart_url')
        Basket.objects.create(owner=request.user, product=product, quantity=kol)
        return redirect('bonaapp:cart_url')
    else:
        messages.error(request,'You can\'t add to cart because the quantity must be greater than zero')
        return redirect('bonaapp:cart_url')
# delete cart item

def delete_cart_item(request):
    basket_pk = request.GET.get('basket_pk')
    buylater_pk = request.GET.get('buylater_pk')
    if buylater_pk:
        buylater = BuyLater.objects.get(pk=buylater_pk)
        buylater.delete()
        return redirect('bonaapp:cart_url')
    if basket_pk:
        basket = Basket.objects.get(pk=basket_pk)
        basket.delete()
        return redirect('bonaapp:cart_url')

def cart(request):
    date_now = datetime.date.today()
    cart = Basket.objects.filter(owner=request.user)
    quantity=None
    for item in cart:
        if item.quantity>0:
            quantity=1
    cart_later = BuyLater.objects.filter(owner=request.user)
    return render(request, 'cart.html', {'cart':cart,'date_now':date_now,'cart_later':cart_later,'quantity':quantity})

def product_detail(request,pk):
    product = Product.objects.get(pk=pk)
    products = Product.objects.all()[:12]
    return render(request, 'product_detail.html', {
        'product':product,
        'products':products
    })

def create_order(request):
    order = Order.objects.filter(owner = request.user)
    basket = Basket.objects.filter(owner=request.user)
    amount = sum([item.quantity for item in basket])
    total = sum([item.total_price() for item in basket])
    address = request.POST.get('address')
    email = request.POST.get('email')
    telephone_number = request.POST.get('telephone_number')

    if address and email and telephone_number:
        order = Order.objects.create(
            address=address,
            email=email,
            telephone_number=telephone_number,
            owner=request.user,
            buy=True,
            date = datetime.datetime.now()
        )
        if order.buy:
            x = None
            for item in basket:
                x = OrderProduct.objects.create(
                    order=order,
                    product=item.product,
                    amount=amount,
                    total=total,
                )
            basket.delete()
            messages.success(request,'Your item has been successfully processed')
            return redirect('bonaapp:history_order_url')
    return render(request,'order.html',{'basket':basket, 'amount':amount,'total':total,'order':order})

def history_order(request):
    order = Order.objects.filter(owner=request.user)
    return render(request,'history_order.html',{'order':order})


def buylater(request,pk):
    date = request.GET.get('date')
    if date:
        basket = Basket.objects.get(pk=pk)
        BuyLater.objects.create(
            owner = request.user,
            date = date,
            product = basket.product,
            quantity = basket.quantity,

        )
        basket.delete()
        messages.success(request,'The product was successfully added to the "buy later" list')
        return redirect('bonaapp:cart_url')


def buynow(request,pk):
    now = BuyLater.objects.get(pk=pk)
    Basket.objects.create(
        owner = request.user,
        product = now.product,
        quantity = now.quantity,
    )
    now.delete()
    return redirect('bonaapp:cart_url')


def return_order(request, pk):
    order = Order.objects.get(pk=pk)
    for item in order.order_product.all():
        Basket.objects.create(
            owner=request.user,
            product=item.product,
            quantity=0.25
        )
    return redirect('bonaapp:cart_url')

def about(request):
    return render(request, 'about.html')

bonaproject/bonaapp/templates/base.html
{% load static %}
{% load categories %}
<!DOCTYPE html>
<html lang="en" style="background-color: rgba(33,241,155,0.29)">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="{% static 'bulma/css/bulma.css' %}">
    <link rel="stylesheet" href="{% static 'css/index.css' %}">
    <link rel="shortcut icon" href="{% static 'images/logo.png' %}" type="image/png">
    <title>
        BonaFressco
    </title>
</head>
<body>
    <nav class="navbar container is-fullhd" role="navigation" aria-label="main navigation">
      <div class="navbar-brand">
        <a class="navbar-item" href="{% url 'bonaapp:home_page' %}">
            <img src="{% static 'images/logo.png' %}" style="width: 100%">
        </a>

        <a role="button" class="navbar-burger" aria-label="menu" aria-expanded="false" data-target="navbarBasicExample">
          <span aria-hidden="true"></span>
          <span aria-hidden="true"></span>
          <span aria-hidden="true"></span>
        </a>
      </div>

      <div id="navbarBasicExample" class="navbar-menu">
        <div class="navbar-start">
          <div class="buttons">
            {% if user.is_authenticated %}
            <a href="{% url 'bonaapp:history_order_url' %}" class="button is-primary is-light is-outlined">
              My History
            </a>
            <a href="{% url 'bonaapp:cart_url' %}" class="button is-light is-warning is-outlined">
              My Cart
            </a>
            {% endif %}
              <form action="{% url 'bonaapp:home_page' %}" method="GET">
                  <input type="search" name="search" class="search" placeholder="Write the product name">
                  <button class="button is-info is-outlined">Search</button>
              </form>
          </div>
        </div>
          <div class="navbar-end">
            <div class="navbar-item">
                {% if not user.is_authenticated %}
                    <a href="{% url 'bonausers:signup' %}" class="button is-primary is-light mr-2 is-outlined">
                      <strong>Sign up</strong>
                    </a>
                    <a href="{% url 'bonausers:login' %}" class="button is-info is-light is-outlined">
                      Log in
                    </a>
                {% else %}
                    <a class="button is-primary is-outlined mr-2">
                      Welcome: {{ user }}
                    </a>
                    <a href="{% url 'bonausers:profile' %}" class="button is-info is-outlined mr-2">
                      My Profile
                    </a>
                    <a href="{% url 'bonausers:logout' %}" class="button is-danger">
                      Log out
                    </a>
                {% endif %}
            </div>
          </div>
      </div>
    </nav>
    {% categories %}

    {% block search %}
    {% endblock search %}

    {% block slider %}
    {% endblock slider %}

    {% block content %}
    {% endblock content %}

    <a href="https://api.whatsapp.com/message/SGMAHKU5L4GCP1?autoload=1&app_absent=0">
        <div class="help">
            <p class="has-text-centered">Can i help you?</p>
        </div>
    </a>

    <footer class="has-background-success-light mt-6 py-6">
        <div class="level content">
            <div class="level-item">
                <p><a type="tel">+971585757411 , +971585343113</a></p>
            </div>
            <div class="level-item">
                <p><a href="{% url 'bonaapp:about_url' %}">About Us</a></p>
            </div>
            <div class="level-item">
                <a href="{% url 'bonaapp:home_page' %}">
                    <img src="{% static 'images/logo.png' %}" alt="" style="height: 50px">
                </a>
            </div>
            <div class="level-item">
                <p><a href="{% url 'bonaapp:about_url' %}#contact">Contact Us</a></p>
            </div>
            <div class="level-item">
                <p><a href="">bonafresco@gmail.com</a></p>
            </div>
        </div>
      <div class="content has-text-centered mt-3">
        <p>
          Copyright BonaFresco 2022. All Rights Reserved.The website content is licensed.
        </p>
      </div>
    </footer>
    <script src="{% static 'js/index.js' %}"></script>
</body>
</html>

bonaproject/bonaapp/templates/cart.html
{% extends 'base.html' %}
{% load static %}


{% block content %}
<section class="section">
    <div class="container">
        {% if messages %}
            <div class="box is-centered has-background-success-light">
                {% for message in messages %}
                    <p class="title has-text-danger has-text-centered">{{ message }}</p>
                {% endfor %}
            </div>
        {% endif %}
        <div class="box">
            <h1 class="title has-text-danger has-text-weight-bold has-text-centered">You cart</h1>
            <div class="content">
                <table class="table">
                    <thead>
                        <tr>
                            <td  style="font-size: 25px; font-weight: 900">product</td>
                            <td  style="font-size: 25px; font-weight: 900">quantity</td>
                            <td  style="font-size: 25px; font-weight: 900">total price</td>
                            <td></td>
                            <td></td>
                        </tr>
                    </thead>
                    <tbody>
                    {% for item in cart %}
                        <tr>
                            <td style="font-size: 25px; font-weight: 600"><a href="{% url 'bonaapp:product_detail_url' item.product.pk %}">{{ item.product.name }}</a></td>
                            <td style="display: flex;font-size: 25px; font-weight: 600;align-items: center" >
                                <a class="counter__btn button is-small is-warning my-1" style="width: 10px;height: 100%" data-direction="minus">-</a>
                                <a class="counter__btn button is-small is-info my-1" style="width: 10px;height: 100%" data-direction="plus">+</a>
                                <form action="{% url 'bonaapp:add_to_cart_url' item.product.pk %}" method="GET" style="display: flex">
                                    <input type="text" value="{{ item.quantity }}" class="counter__value" name="kol">
                                    <button class="button is-info">Change</button>
                                </form>
                            </td>
                            <td style="font-size: 25px; font-weight: 600">{{ item.total_price }} AED</td>
                            <td>
                                <figure class="image is-vcentered" style="width: 35px ;">
                                    <a href="{% url 'bonaapp:delete_cart_item' %}?basket_pk={{item.pk}}"><img src="{% static 'icons/trash.png' %}" alt=""></a>
                                </figure>
                            </td>
                            <td>
                                <a class="js-modal-trigger button" style="background-color: rgba(255,245,0,0.45)" data-target="modal-js-example">Buy later</a>
                            </td>
                        </tr>
                        <div class="modal" id="modal-js-example">
                          <div class="modal-background"></div>
                          <div class="modal-card">
                            <header class="modal-card-head">
                              <p class="modal-card-title">Modal title</p>
                              <button class="delete" aria-label="close"></button>
                            </header>
                            <section class="modal-card-body">
                                <form action="{% url 'bonaapp:buy_later_url' item.pk %}" id="later" method="GET">
                                    <input type="date" class="input" min="{{ date_now|date:'d.m.Y' }}" name="date">
                                </form>
                            </section>
                            <footer class="modal-card-foot">
                              <button class="button is-success" form="later">Ok</button>
                              <button class="button" name="text">Cancel</button>
                            </footer>
                          </div>
                        </div>
                    {% empty %}
                        <h1 class="title has-text-danger-dark has-text-centered">Empty</h1>
                    {% endfor %}
                    </tbody>
                </table>
                <div  class="buttons is-centered">
                    <a href="{% url 'bonaapp:home_page' %}" class="button is-warning">Go to home page</a>
                    {% if cart and quantity %}
                    <a href="{% url 'bonaapp:create_order_url' %}" class="button is-primary">Checkout</a>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
</section>




<section class="section">
    <div class="container">
        <div class="box">
            <h1 class="title has-text-danger has-text-weight-bold has-text-centered">Buy Later</h1>
            <div class="content">
                <table class="table">
                    <thead>
                        <tr>
                            <td  style="font-size: 25px; font-weight: 900">product</td>
                            <td  style="font-size: 25px; font-weight: 900">quantity</td>
                            <td  style="font-size: 25px; font-weight: 900">total price</td>
                            <td style="font-size: 25px; font-weight: 900">Buy Date</td>
                            <td></td>
                            <td></td>
                        </tr>
                    </thead>
                    <tbody>
                    {% for item in cart_later %}
                        <tr>
                            <td style="font-size: 25px; font-weight: 600">{{ item.product.name }}</td>
                            <td style="display: flex;font-size: 25px; font-weight: 600;align-items: center" >
                                {{ item.quantity }}
                            </td>
                            <td style="font-size: 25px; font-weight: 600">
                                {{ item.total_price }}
                            </td>
                            <td style="font-size: 25px; font-weight: 600">
                                {{ item.date|date:'d-m-Y' }}
                            </td>
                            <td>
                                <figure class="image is-vcentered" style="width: 35px ;">
                                    <a href="{% url 'bonaapp:delete_cart_item' %}?buylater_pk={{item.pk}}"><img src="{% static 'icons/trash.png' %}" alt=""></a>
                                </figure>
                            </td>
                            <td>
                                <a href="{% url 'bonaapp:buy_now_url' item.pk %}" class="button" style="background-color: rgba(255,245,0,0.45)" >Buy Now</a>
                            </td>
                        </tr>
                    {% empty %}
                        <h1 class="title has-text-danger-dark has-text-centered">Empty</h1>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</section>
{% endblock content %}

bonaproject/bonaapp/templates/category-detail.html
{% extends 'base.html' %}

{% block title %}
Home Page
{% endblock title %}

{% block content %}
    <section class="section">
        <div class="container is-fullhd">
            <div class="columns is-multiline ">
                {% for item in category.product_set.all %}
                    <div class="column card is-3 mx-auto mb-5">
                        <div class="card-header">
                            <div class="card-header-icon">
                                {% if item.discounted_product %}
                                    <span class="has-background-success has-text-white py-2 px-4" style="border-radius: 10px">discount</span>
                                {% endif %}
                            </div>
                            <div class="card-header-title is-centered">
                                <a href="{% url 'bonaapp:product_detail_url' item.pk %}">{{ item.name }}</a>
                            </div>
                        </div>
                        <div class="card-image">
                            <figure class="image">
                                <img src="{{ item.image.url }}" alt="">
                            </figure>
                        </div>
                        <div class="card-footer">
                            <div class="card-footer-item">
                                {% if item.discounted_product %}
                                    <span class="has-background-info has-text-white py-2 px-4 mx-1" style="border-radius: 10px;">{{ item.discounted_price }}AED
                                    <br>
                                    kg,liter</span>
                                {% else %}
                                    <span class="has-background-info has-text-white py-2 px-4 mx-1" style="border-radius: 10px;">{{ item.price }}AED
                                    <br>
                                    kg,liter</span>
                                {% endif %}
                            </div>
                            <div class="card-footer-item" >
                                {% if user.is_authenticated %}
                                <form action="{% url 'bonaapp:add_to_cart_url' item.pk %}" method="GET" style="display: flex" class="counter is-vcentered">
                                    <a class="counter__btn button is-small is-warning my-1" style="width: 10px;height: 100%" data-direction="minus">-</a>
                                    <a class="counter__btn button is-small is-info my-1" style="width: 10px;height: 100%" data-direction="plus">+</a>
                                    <input type="text" value="0.25" class="counter__value input is-size-7" name="kol" style="width: 50px;height: 40px">
                                    <input type="submit" class="button is-success" value="buy" >
                                </form>
                                {% endif %}
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>
    </section>
{% endblock content %}

bonaproject/bonaapp/templates/history_order.html
{% extends 'base.html' %}

{% block content %}
<section class="section">
    <div class="container box">
        {% if messages %}
            <div class="box is-centered has-background-success">
                {% for message in messages %}
                    <p class="title has-text-light has-text-centered">{{ message }}</p>
                {% endfor %}
            </div>
        {% endif %}
        <h2 class="subtitle has-text-centered">Your History Order</h2>
        <table class="table is-fullwidth">
            <thead>
                <tr>
                    <td><b>address</b></td>
                    <td><b>date</b></td>
                    <td><b>more detailed</b></td>
                </tr>
            </thead>
            <tbody>
                {% for item in order %}
                    <tr>
                    <td><b>{{ item.address }}</b></td>
                    <td><b>{{ item.date|date:"d.m.Y" }}</b></td>
                    <td>
                        <p><b>Product Name: </b>
                        {% for a in item.order_product.all %}
                            {{ a.product.name }}
                        {% endfor %}
                        </p>
                        {% for a in item.order_product.all %}
                            <p><b>total</b> : {{ a.total }}</p>
                            <p class="mb-2"><b>amount</b> : {{ a.amount }}</p>
                        {% endfor %}
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</section>
{% endblock content %}

bonaproject/bonaapp/templates/order.html
{% extends 'base.html' %}

{% block content %}
<section class="section">
    <div class="container">
        {% if messages %}
            <div class="box is-centered has-background-danger">
                {% for message in messages %}
                    <p class="title has-text-light has-text-centered">{{ message }}</p>
                {% endfor %}
            </div>
        {% endif %}
        <div class="columns is-justify-content-space-between">
            <div class="column is-4 box p-6">
                <p class="subtitle has-text-centered">fill in the fields to place an order</p>
                <form method="POST">
                    {% csrf_token %}
                    <input type="text" class="input my-2" name="address" placeholder="Address" required>
                    <input type="email" class="input my-2" name="email" placeholder="Email" required>
                    <input type="text" class="input my-2" name="telephone_number" placeholder="Phone number" required>
                    <button class="button is-info">Checkout</button>
                </form>
            </div>
            <div class="column is-7 box is-centered ">
                <p class="subtitle is-size-3 has-text-centered is-vcentered">Basket <a href="{% url 'bonaapp:cart_url' %}" class="button is-warning">Edit</a></p>
                <table class="table is-fullwidth">
                    <thead>
                        <tr>
                            <td>product</td>
                            <td>price</td>
                            <td>quantity</td>
                            <td>total price</td>
                        </tr>
                    </thead>
                    <tbody>
                        {% for item in basket %}
                            <tr>
                                <td>{{ item.product.name }}</td>
                                <td>{{ item.product.price }} AED</td>
                                <td>{{ item.quantity }} kg \ liter</td>
                                <td>{{ item.total_price }} AED</td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
                <p class="subtitle has-text-centered is-size-5">
                    <span class="has-text-info has-text-weight-bold">total price: <span class="has-text-black">{{ total }}</span> AED</span>
                </p>
            </div>
        </div>
    </div>
</section>

<section class="section">
    <div class="container box">
        {% if messages %}
            <div class="box is-centered has-background-success">
                {% for message in messages %}
                    <p class="title has-text-light has-text-centered">{{ message }}</p>
                {% endfor %}
            </div>
        {% endif %}
        <h2 class="subtitle has-text-centered">Your History Order</h2>
        <table class="table is-fullwidth">
            <thead>
                <tr>
                    <td><b>address</b></td>
                    <td><b>date</b></td>
                    <td><b>more detailed</b></td>
                    <td></td>
                </tr>
            </thead>
            <tbody>
                {% for item in order %}
                    <tr>
                    <td><b>{{ item.address }}</b></td>
                    <td><b>{{ item.date|date:"d.m.Y" }}</b></td>
                    <td>
                        <p><b>Product Name: </b>
                        {% for a in item.order_product.all %}
                            {{ a.product.name }}
                        {% endfor %}
                        </p>
                    </td>
                    <td>
                        <a href="{% url 'bonaapp:return_order_url' item.pk %}" class="button is-success">Buy</a>
                    </td>
                </tr>
                {% empty %}
                    <h1 class="title has-text-danger-dark has-text-centered">Empty</h1>
                {% endfor %}
            </tbody>
        </table>
    </div>
</section>
{% endblock content %}

bonaproject/bonaapp/templates/product_detail.html
{% extends 'base.html' %}


{% block content %}
    <div class="container">
        <div class="columns is-justify-content-space-between">
            <div class="column is-6 box">
                <figure class="image">
                    <img src="{{ product.image.url }}" alt="">
                </figure>
            </div>
            <div class="column is-5 box">
                <p class="subtitle has-text-centered is-size-3">{{ product.name }}</p>
                <hr>
                <div class="content py-2">
                    {{ product.description }}
                </div>
                <p class="subtitle">country: {{ product.country }}</p>
                <p class="subtitle">price: {{product.price}}</p>
                <p class="subtitle ">date: {{ product.date }}</p>
                <div class="buttons">
                    <a href="{% url 'bonaapp:add_to_cart_url' %}?product={{ product.pk }}" class="button is-primary">Buy</a>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}